const metrics = [
  { value: "50K+", label: "Apps Built", description: "And counting" },
  { value: "100M+", label: "Lines of Code", description: "Generated by AI" },
  { value: "<30s", label: "Avg Build Time", description: "Idea to app" },
  { value: "98%", label: "Satisfaction", description: "From our users" },
]

export function ImpactSection() {
  return (
    <section id="metrics" className="px-4 py-20 sm:px-6 sm:py-24">
      <div className="mx-auto max-w-6xl rounded-[2rem] border border-border bg-card px-5 py-10 sm:px-8 sm:py-12 lg:px-12">
        <div className="mb-12 text-center">
          <p className="text-sm font-medium text-accent-soft-foreground uppercase tracking-wider mb-4">By the numbers</p>
          <h2 className="font-display text-3xl md:text-4xl font-bold text-foreground mb-4">Powering the next generation</h2>
          <p className="text-muted-foreground max-w-lg mx-auto text-balance">
            Builders around the world are creating polished web apps faster with Lotus.build.
          </p>
        </div>

        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
          {metrics.map((metric) => (
            <div
              key={metric.label}
              className="group relative overflow-hidden rounded-2xl border border-border bg-surface-raised p-6 text-center transition-all duration-300 hover:-translate-y-0.5 hover:border-border-strong hover:bg-primary"
            >
              <div className="absolute inset-0 bg-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300" />
              <div className="relative">
                <p className="font-display text-3xl md:text-4xl font-bold text-foreground mb-1 group-hover:text-primary-foreground transition-colors">
                  {metric.value}
                </p>
                <p className="text-sm font-medium text-muted-foreground mb-1 transition-colors group-hover:text-primary-foreground/85">{metric.label}</p>
                <p className="text-xs text-muted-foreground transition-colors group-hover:text-primary-foreground/70">{metric.description}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  )
}


